;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	me/set-mark
	nonincremental-search-forward
	))

(setq mc/cmds-to-run-once
      '(
	kill-region
	me/multiple-words
	yas-expand
	))
