;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	me/set-mark
	nonincremental-search-forward
	orgtbl-self-insert-command
	smex
	))

(setq mc/cmds-to-run-once
      '(
	beginning-of-buffer
	kill-region
	me/multiple-words
	me/select-line
	org-self-insert-command
	shell-command
	yas-expand
	))
